import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../utils/app_color.dart';
import '../../utils/app_theme.dart';
import '../../utils/app_typography.dart';
import '../shared/custom_bottom_nav.dart';
import 'notification_settings_viewmodel.dart';

/// VIEW
/// "Notification Preferences" screen: alert opt-ins grouped into
/// Field Intelligence / Environment / Account Settings sections.
class NotificationSettingsView extends StatelessWidget {
  const NotificationSettingsView({super.key});

  @override
  Widget build(BuildContext context) {
    final vm = context.watch<NotificationSettingsViewModel>();

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: AppColors.background,
        elevation: 0,
        leading: const BackButton(color: AppColors.primaryDark),
        title: const Text('Profile & Payments', style: TextStyle(color: AppColors.primaryDark, fontWeight: FontWeight.bold)),
        actions: [
          Padding(
            padding: const EdgeInsets.only(right: 16),
            child: CircleAvatar(radius: 16, backgroundColor: AppColors.accent2, child: const Icon(Icons.person, size: 18, color: AppColors.primaryDark)),
          ),
        ],
      ),
      bottomNavigationBar: const CustomBottomNav(currentIndex: 4),
      body: SafeArea(
        child: vm.isLoading
            ? const Center(child: CircularProgressIndicator(color: AppColors.primaryDark))
            : ListView(
                padding: const EdgeInsets.fromLTRB(20, 8, 20, 20),
                children: [
                  Text('Notification Preferences', style: AppTypography.headlineLgMobile()),
                  const SizedBox(height: 6),
                  const Text(
                    'Stay informed about your fields. Customize what alerts you receive and when.',
                    style: TextStyle(color: AppColors.textMuted, fontSize: 15, height: 1.4),
                  ),
                  const SizedBox(height: 20),
                  _SectionCard(
                    label: 'FIELD INTELLIGENCE',
                    children: [
                      _NotificationRow(
                        title: 'Crop Scan Results',
                        description: 'Receive alerts when AI analysis of your latest drone or satellite imagery is complete, highlighting areas needing attention.',
                        value: vm.prefs.cropScanResults,
                        onChanged: vm.toggleCropScanResults,
                      ),
                      const Divider(height: 32),
                      _NotificationRow(
                        title: 'Daily Farming Tips',
                        description: 'Get a daily digest of best practices, tailored to your current crop cycle and local soil conditions, generated by our agronomy AI.',
                        value: vm.prefs.dailyFarmingTips,
                        onChanged: vm.toggleDailyFarmingTips,
                      ),
                    ],
                  ),
                  const SizedBox(height: 20),
                  _SectionCard(
                    label: 'ENVIRONMENT',
                    children: [
                      _NotificationRow(
                        title: 'Weather Alerts',
                        description: 'Immediate notifications for severe weather events (frost, heavy rain, high winds) approaching your mapped fields.',
                        value: vm.prefs.weatherAlerts,
                        onChanged: vm.toggleWeatherAlerts,
                      ),
                    ],
                  ),
                  const SizedBox(height: 20),
                  _SectionCard(
                    label: 'ACCOUNT SETTINGS',
                    children: [
                      _NotificationRow(
                        title: 'Account Updates',
                        description: 'Billing notifications, subscription changes, and important security alerts.',
                        value: vm.prefs.accountUpdates,
                        onChanged: vm.toggleAccountUpdates,
                      ),
                    ],
                  ),
                ],
              ),
      ),
    );
  }
}

class _SectionCard extends StatelessWidget {
  final String label;
  final List<Widget> children;

  const _SectionCard({required this.label, required this.children});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: AppColors.cardWhite,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: AppColors.primary.withOpacity(0.1)),
        boxShadow: AppTheme.cardShadow,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(label, style: const TextStyle(fontSize: 11, color: AppColors.textMuted, letterSpacing: 0.8, fontWeight: FontWeight.w700)),
          const SizedBox(height: 16),
          ...children,
        ],
      ),
    );
  }
}

class _NotificationRow extends StatelessWidget {
  final String title;
  final String description;
  final bool value;
  final ValueChanged<bool> onChanged;

  const _NotificationRow({
    required this.title,
    required this.description,
    required this.value,
    required this.onChanged,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(title, style: AppTypography.headlineMd().copyWith(fontSize: 16)),
              const SizedBox(height: 4),
              Text(description, style: const TextStyle(color: AppColors.textMuted, fontSize: 13, height: 1.4)),
            ],
          ),
        ),
        const SizedBox(width: 12),
        Switch(
          value: value,
          onChanged: onChanged,
          activeColor: AppColors.onPrimary,
          activeTrackColor: AppColors.primaryDark,
          inactiveThumbColor: AppColors.cardWhite,
          inactiveTrackColor: AppColors.surfaceContainerHighest,
        ),
      ],
    );
  }
}
